
name: 'dbt_external_tables_integration_tests'
version: '1.0'

profile: 'integration_tests'

config-version: 2

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# FIXME: query-comment must be disabled for Athena to work because /* block comments are unsupported in Athena DML
# Removing this line will result in a Runtime Error during the integration test 
#   `2 of 5 (2) create external table dbt.people_csv_partitioned ...`. The error is
#   "FAILED: ParseException line 1:0 cannot recognize input near '/' '*' '{".
# Is there a better way around this?
query-comment: ''

dispatch:
  - macro_namespace: dbt_external_tables
    search_order: ['dbt_external_tables_integration_tests', 'dbt_external_tables']

seeds:
  +quote_columns: false

sources:
  dbt_external_tables_integration_tests:
    plugins:
      athena:
        +enabled: "{{ target.type == 'athena' }}"
      redshift:
        +enabled: "{{ target.type == 'redshift' }}"
      snowflake:
        +enabled: "{{ target.type == 'snowflake' }}"
      bigquery:
        +enabled: "{{ target.type == 'bigquery' }}"
      spark:
        +enabled: "{{ target.type == 'spark' }}"
      synapse:
        +enabled: "{{ target.type == 'synapse' }}"
      azuresql:
        +enabled: "{{ target.type == 'sqlserver' }}"

tests:
  dbt_external_tables_integration_tests:
    plugins:
      athena:
        +enabled: "{{ target.type == 'athena' }}"
      redshift:
        +enabled: "{{ target.type == 'redshift' }}"
      snowflake:
        +enabled: "{{ target.type == 'snowflake' }}"
      bigquery:
        +enabled: "{{ target.type == 'bigquery' }}"
      spark:
        +enabled: "{{ target.type == 'spark' }}"
      synapse:
        +enabled: "{{ target.type == 'synapse' }}"
      azuresql:
        +enabled: "{{ target.type == 'sqlserver' }}"
